# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/index.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from ..proto import frame_pb2 as proto_dot_frame__pb2
from ..proto import series_pb2 as proto_dot_series__pb2
from syft.proto.core.common import (
    common_object_pb2 as proto_dot_core_dot_common_dot_common__object__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/index.proto",
    package="pandas",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x11proto/index.proto\x12\x06pandas\x1a%proto/core/common/common_object.proto\x1a\x12proto/series.proto\x1a\x11proto/frame.proto"T\n\x0bPandasIndex\x12!\n\x02id\x18\x01 \x01(\x0b\x32\x15.syft.core.common.UID\x12"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.pandas.PandasSeries"]\n\x10PandasMultiIndex\x12!\n\x02id\x18\x01 \x01(\x0b\x32\x15.syft.core.common.UID\x12&\n\x05\x66rame\x18\x02 \x01(\x0b\x32\x17.pandas.PandasDataFrameb\x06proto3',
    dependencies=[
        proto_dot_core_dot_common_dot_common__object__pb2.DESCRIPTOR,
        proto_dot_series__pb2.DESCRIPTOR,
        proto_dot_frame__pb2.DESCRIPTOR,
    ],
)


_PANDASINDEX = _descriptor.Descriptor(
    name="PandasIndex",
    full_name="pandas.PandasIndex",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="pandas.PandasIndex.id",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="data",
            full_name="pandas.PandasIndex.data",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=107,
    serialized_end=191,
)


_PANDASMULTIINDEX = _descriptor.Descriptor(
    name="PandasMultiIndex",
    full_name="pandas.PandasMultiIndex",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="pandas.PandasMultiIndex.id",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="frame",
            full_name="pandas.PandasMultiIndex.frame",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=193,
    serialized_end=286,
)

_PANDASINDEX.fields_by_name[
    "id"
].message_type = proto_dot_core_dot_common_dot_common__object__pb2._UID
_PANDASINDEX.fields_by_name["data"].message_type = proto_dot_series__pb2._PANDASSERIES
_PANDASMULTIINDEX.fields_by_name[
    "id"
].message_type = proto_dot_core_dot_common_dot_common__object__pb2._UID
_PANDASMULTIINDEX.fields_by_name[
    "frame"
].message_type = proto_dot_frame__pb2._PANDASDATAFRAME
DESCRIPTOR.message_types_by_name["PandasIndex"] = _PANDASINDEX
DESCRIPTOR.message_types_by_name["PandasMultiIndex"] = _PANDASMULTIINDEX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PandasIndex = _reflection.GeneratedProtocolMessageType(
    "PandasIndex",
    (_message.Message,),
    {
        "DESCRIPTOR": _PANDASINDEX,
        "__module__": "proto.index_pb2"
        # @@protoc_insertion_point(class_scope:pandas.PandasIndex)
    },
)
_sym_db.RegisterMessage(PandasIndex)

PandasMultiIndex = _reflection.GeneratedProtocolMessageType(
    "PandasMultiIndex",
    (_message.Message,),
    {
        "DESCRIPTOR": _PANDASMULTIINDEX,
        "__module__": "proto.index_pb2"
        # @@protoc_insertion_point(class_scope:pandas.PandasMultiIndex)
    },
)
_sym_db.RegisterMessage(PandasMultiIndex)


# @@protoc_insertion_point(module_scope)
