# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/loc.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from ..proto import frame_pb2 as proto_dot_frame__pb2
from ..proto import series_pb2 as proto_dot_series__pb2
from syft.proto.core.common import (
    common_object_pb2 as proto_dot_core_dot_common_dot_common__object__pb2,
)
from syft.proto.lib.python import string_pb2 as proto_dot_lib_dot_python_dot_string__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/loc.proto",
    package="pandas",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0fproto/loc.proto\x12\x06pandas\x1a%proto/core/common/common_object.proto\x1a\x1dproto/lib/python/string.proto\x1a\x12proto/series.proto\x1a\x11proto/frame.proto"\xb8\x01\n\tPandasLoc\x12!\n\x02id\x18\x01 \x01(\x0b\x32\x15.syft.core.common.UID\x12%\n\x04name\x18\x02 \x01(\x0b\x32\x17.syft.lib.python.String\x12&\n\x06series\x18\x03 \x01(\x0b\x32\x14.pandas.PandasSeriesH\x00\x12(\n\x05\x66rame\x18\x04 \x01(\x0b\x32\x17.pandas.PandasDataFrameH\x00\x42\x0f\n\rFrameOrSeriesb\x06proto3',
    dependencies=[
        proto_dot_core_dot_common_dot_common__object__pb2.DESCRIPTOR,
        proto_dot_lib_dot_python_dot_string__pb2.DESCRIPTOR,
        proto_dot_series__pb2.DESCRIPTOR,
        proto_dot_frame__pb2.DESCRIPTOR,
    ],
)


_PANDASLOC = _descriptor.Descriptor(
    name="PandasLoc",
    full_name="pandas.PandasLoc",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="pandas.PandasLoc.id",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="pandas.PandasLoc.name",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="series",
            full_name="pandas.PandasLoc.series",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="frame",
            full_name="pandas.PandasLoc.frame",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="FrameOrSeries",
            full_name="pandas.PandasLoc.FrameOrSeries",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=137,
    serialized_end=321,
)

_PANDASLOC.fields_by_name[
    "id"
].message_type = proto_dot_core_dot_common_dot_common__object__pb2._UID
_PANDASLOC.fields_by_name[
    "name"
].message_type = proto_dot_lib_dot_python_dot_string__pb2._STRING
_PANDASLOC.fields_by_name["series"].message_type = proto_dot_series__pb2._PANDASSERIES
_PANDASLOC.fields_by_name["frame"].message_type = proto_dot_frame__pb2._PANDASDATAFRAME
_PANDASLOC.oneofs_by_name["FrameOrSeries"].fields.append(
    _PANDASLOC.fields_by_name["series"]
)
_PANDASLOC.fields_by_name["series"].containing_oneof = _PANDASLOC.oneofs_by_name[
    "FrameOrSeries"
]
_PANDASLOC.oneofs_by_name["FrameOrSeries"].fields.append(
    _PANDASLOC.fields_by_name["frame"]
)
_PANDASLOC.fields_by_name["frame"].containing_oneof = _PANDASLOC.oneofs_by_name[
    "FrameOrSeries"
]
DESCRIPTOR.message_types_by_name["PandasLoc"] = _PANDASLOC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PandasLoc = _reflection.GeneratedProtocolMessageType(
    "PandasLoc",
    (_message.Message,),
    {
        "DESCRIPTOR": _PANDASLOC,
        "__module__": "proto.loc_pb2"
        # @@protoc_insertion_point(class_scope:pandas.PandasLoc)
    },
)
_sym_db.RegisterMessage(PandasLoc)


# @@protoc_insertion_point(module_scope)
