apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grid-vpn-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /vpn
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 8080
